[package]
name = "zing"
version = "0.1.0"
authors = ["Aske Simon Christensen <askesc@gmail.com>"]
edition = "2018"
build = "build.rs" # LALRPOP preprocessing

[dependencies]
lalrpop-util = "0.17.2"
regex = "0.2.0"

[build-dependencies]
lalrpop = "0.17.2"
